### ISSUE TITLE
LUA Error V1.17

### ISSUE THREAD

**Issue by Lanacan** [oUF-wow/oUF_MovableFrames#11]
```
Message: Interface\AddOns\oUF_MovableFrames\movable.lua:470: attempt to call method 'SetBackdrop' (a nil value)
Time: Fri Nov 13 09:48:41 2020
Count: 2
Stack: Interface\AddOns\oUF_MovableFrames\movable.lua:470: attempt to call method 'SetBackdrop' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBackdrop'
[string "@Interface\AddOns\oUF_MovableFrames\movable.lua"]:470: in function <Interface\AddOns\oUF_MovableFrames\movable.lua:461>
[string "@Interface\AddOns\oUF_MovableFrames\movable.lua"]:1011: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5073: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4737: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4773: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = <function> defined =[C]:-1
```

**Comment by p3lim** [comment]
Try updating your addons.

**Comment by Lanacan** [comment]
I pulled it today from WoW Interface (https://www.wowinterface.com/downloads/fileinfo.php?id=15425#info). 

I downloaded it again now and this was the TOC:

## Interface: 40100
## Title: oUF: MovableFrames
## Author: Haste
## Version: 1.16
## OptionalDeps: oUF
## SavedVariables: bb08df87101dd7f2161e5b77cf750f753c58ef1b
## Notes: Easily move frames created by oUF.

## X-eMail: troeks@gmail.com
## X-SavedVariables: bb08df87101dd7f2161e5b77cf750f753c58ef1b
## X-SlashCmdList: /omf

movable.lua

**Comment by haste** [comment]
Looks like I messed up updating it... Updated the zip to be 1.17. Not sure how I didn't include it last round.
